/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#0c1e26",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#444749",
        "on-surface-variant": "#414755",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#384953",
        surface: "#f8f9ff",
        outline: "#717786",
        "on-primary-fixed-variant": "#004493",
        error: "#ba1a1a",
        "inverse-surface": "#213145",
        "inverse-primary": "#adc6ff",
        "tertiary-fixed-dim": "#c4c7c9",
        primary: "#0058bc",
        "tertiary-container": "#727577",
        "secondary-container": "#d3e5f1",
        "on-error-container": "#93000a",
        "primary-container": "#0070eb",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#191c1e",
        "on-error": "#ffffff",
        "surface-tint": "#005bc1",
        tertiary: "#595c5e",
        "secondary-fixed": "#d3e5f1",
        "on-primary-fixed": "#001a41",
        "outline-variant": "#c1c6d7",
        "on-surface": "#0b1c30",
        "surface-container": "#e5eeff",
        "primary-fixed": "#d8e2ff",
        "tertiary-fixed": "#e0e3e5",
        "on-tertiary-container": "#fbfdff",
        "on-primary-container": "#fefcff",
        "surface-container-low": "#eff4ff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b7c9d5",
        "surface-container-highest": "#d3e4fe",
        secondary: "#50616b",
        "surface-dim": "#cbdbf5",
        "on-tertiary": "#ffffff",
        "surface-variant": "#d3e4fe",
        "on-background": "#0b1c30",
        "primary-fixed-dim": "#adc6ff",
        "on-secondary-container": "#566771",
        "surface-container-high": "#dce9ff",
        background: "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "dark-bg": "#0f172a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "base-unit": "4px",
        "margin-mobile": "20px",
        "stack-lg": "32px",
        "gutter-md": "16px",
        "stack-sm": "8px",
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-temp": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-temp": ["84px", { lineHeight: "90px", letterSpacing: "-0.04em", fontWeight: "300" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
